## Задача 2

На складе лежат разные фрукты в разном количестве.
Нужно написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе

In [30]:
fruits = {'Lemon':10,'Apricot':20,'Avocado':30,'Apple':10,'Banana': 12, 'Fig': 17, 'Kiwi': 11}
sum = 0
for item in fruits.values():
    sum += item
print(f'Общее количество всех фруктов на складе равно {sum}.')

Общее количество всех фруктов на складе равно 110.

## Задача 3

Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты  
[100, 125, -90, 345, 655, -1, 0, 200]  
Используйте list comprehensions

In [31]:
def get_price(price):
    return price if price > 0 else 0

sumOfPrices = 0
orig_prices = [100, 125, -90, 345, 655, -1, 0, 200]
prices = [get_price(i) for i in orig_prices]

for i in prices: sumOfPrices += i
print("Уточненный список с затратами на рекламу: ", prices)
print("Суммарные затраты: ", sumOfPrices)

Уточненный список с затратами на рекламу:  [100, 125, 0, 345, 655, 0, 0, 200]
Суммарные затраты:  1425

## Задача 4
Даны два списка.  
Дата покупки  
['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']  
Суммы покупок по датам  
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]  
### 4.1  
Найдите, какая выручка у компании в ноябре.

In [32]:
date = ['2021-09-14', '2021-12-15', '2021-09-08',
      '2021-12-05', '2021-10-09', '2021-09-30',
      '2021-12-22', '2021-11-29', '2021-12-24',
      '2021-11-26', '2021-10-27', '2021-12-18',
      '2021-11-09', '2021-11-23', '2021-09-27',
      '2021-10-02', '2021-12-27', '2021-09-20',
      '2021-12-13', '2021-11-01', '2021-11-09',
      '2021-12-06', '2021-12-08', '2021-10-09',
      '2021-10-31', '2021-09-30', '2021-11-09',
      '2021-12-13', '2021-10-26', '2021-12-09']
money = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944,
      5723, 3701, 4471, 651, 7037, 4274, 6275, 4988,
      6930, 2971, 6592, 2004, 2822, 519, 3406, 2732,
      5015, 2008, 316, 6333, 5700, 2887]
 
import pandas as pd
 
df = pd.DataFrame(money, index=pd.to_datetime(date))
print(f'Выручка компании в ноябре составила: {df[df.index.month==11].sum()[0]}')

Выручка компании в ноябре составила: 25098

### 4.2
Найдите выручку компании в зависимости от месяца
Для этого напишите функцию, которая на вход принимает список с датами и список с выручкой, а на выходе словарь, где ключи - это месяцы, а значения - это выручка.
Используйте аннотирование типов.

In [33]:
def sum_in_month(date: list, money: list) -> dict:
    res = {}
    for d, m in zip(date, money):
        if d[5:7] in res.keys():
            res[d[5:7]] = res[d[5:7]] + m
        else:
            res[d[5:7]] = m
    return res
 
print(sum_in_month(date, money))

{'09': 25647, '12': 45452, '10': 28645, '11': 25098}